codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 2%
        paths:
          - 'src'
    patch:
      default:
        target: 100%
        threshold: 2%

ignore:
  - 'src/**/*.test.ts'
  - 'src/**/*.spec.ts'
  - 'src/services/hasura/generated-graphql/**'
  - 'src/services/hasura/codegen.ts'
  - 'src/services/hashnode/generated-graphql/**'
  - 'src/services/hashnode/codegen.ts'

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  show_carryforward_flags: true

github_checks:
  annotations: true
