name: Deploy

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    environment:
      name: prod

    steps:
      # Step 1: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: shinabr2
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build and Push Docker Image to Docker Hub
      - name: Build and Push Gateway Image
        id: build-and-push-gateway
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile.gateway
          platforms: linux/amd64,linux/arm64
          push: true
          tags: shinabr2/sworld-backend:gateway-${{ github.ref_name }}-${{ github.sha }}

      - name: Build and Push Compute Image
        id: build-and-push-compute
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile.compute
          platforms: linux/amd64,linux/arm64
          push: true
          tags: shinabr2/sworld-backend:compute-${{ github.ref_name }}-${{ github.sha }}

      - name: Build and Push IO Image
        id: build-and-push-io
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile.io
          platforms: linux/amd64,linux/arm64
          push: true
          tags: shinabr2/sworld-backend:io-${{ github.ref_name }}-${{ github.sha }}

      - id: authentication
        name: Authentication
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GH_ACTIONS_SWORLD }}'

      # Step 4: Deploy Docker Image to Google Cloud Run
      - name: Deploy Gateway to Cloud Run
        run: |
          IMAGE_TAG="shinabr2/sworld-backend:gateway-${{ github.ref_name }}-${{ github.sha }}"
          gcloud run deploy gateway \
            --image $IMAGE_TAG \
            --platform managed \
            --port 4000 \
            --region asia-southeast1 \
            --allow-unauthenticated
      - name: Deploy Compute to Cloud Run
        run: |
          IMAGE_TAG="shinabr2/sworld-backend:compute-${{ github.ref_name }}-${{ github.sha }}"
          gcloud run deploy compute \
            --image $IMAGE_TAG \
            --platform managed \
            --port 4000 \
            --region asia-southeast1
      - name: Deploy IO to Cloud Run
        run: |
          IMAGE_TAG="shinabr2/sworld-backend:io-${{ github.ref_name }}-${{ github.sha }}"
          gcloud run deploy io \
            --image $IMAGE_TAG \
            --platform managed \
            --port 4000 \
            --region asia-southeast1
