name: Deploy IO to dev

on:
  push:
    branches:
      - main
    paths:
      - 'src/apps/io/**'
      - 'Dockerfile.io'
      - 'package.json'
      - 'package-lock.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: shinabr2
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push IO Image
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile.io
          platforms: linux/amd64,linux/arm64
          push: true
          tags: shinabr2/sworld-backend:io-${{ github.ref_name }}-${{ github.sha }}

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GH_ACTIONS_MY_WORLD_DEV }}'

      - name: Deploy to Cloud Run
        run: |
          IMAGE_TAG="shinabr2/sworld-backend:io-${{ github.ref_name }}-${{ github.sha }}"
          gcloud run deploy io \
            --image $IMAGE_TAG \
            --platform managed \
            --port 4000 \
            --region asia-southeast1