name: Deploy IO to PROD

on:
  push:
    branches:
      - main
    paths:
      - 'src/apps/io/**'
      - 'Dockerfile.io'
      - 'package.json'
      - 'package-lock.json'

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:ci
        env:
          NODE_ENV: test
          CI: true
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: prod

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: shinabr2
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push IO Image
        id: build-and-push-io
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile.io
          platforms: linux/amd64,linux/arm64
          push: true
          tags: shinabr2/sworld-backend:io-${{ github.ref_name }}-${{ github.sha }}

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GH_ACTIONS_SWORLD }}'

      - name: Deploy IO to Cloud Run
        run: |
          IMAGE_TAG="shinabr2/sworld-backend:io-${{ github.ref_name }}-${{ github.sha }}"
          gcloud run deploy io \
            --image $IMAGE_TAG \
            --platform managed \
            --port 4000 \
            --region asia-southeast1